
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tonyh
 */
public class View extends javax.swing.JFrame {
    
    BeginningStoryPanel beginningpanel;
    CabinPanel cabinpanel;

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }
    
    public void centerMe(){
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screen.getWidth() - getWidth()) /2);
        int y = (int) ((screen.getHeight() -getHeight()) /2);
        setLocation(x, y);

    }

//JFrame - Desktop Pane + Login
    public JDesktopPane getDesktopPane(){
        return DesktopPane;
    }
    public JInternalFrame getLoginInternalFrame(){
        return loginInternalFrame;
    }
    public JTextField getLoginUsername(){
        return usernameField;
    }
    public JPasswordField getLoginPassword(){
        return passwordField;
    }
    public JButton getLoginButton(){
        return loginButton;
    }
    public JLabel getCreateAccountButton(){
        return createAccountLabel;
    }
    //Listeners for Login
    public void addsubmitListener(ActionListener listener){
        this.loginButton.addActionListener(listener);
    }
    
    public void addregisterListener(MouseListener listener){
        this.createAccountLabel.addMouseListener(listener);
    }

//Register Dialog
    public JTextField getRegisterUsername(){
        return registerUsernameField;
    }
    public JPasswordField getRegisterPassword(){
        return registerPasswordField;
    }
    public JButton getRegisterButton(){
        return registerButton;
    }
    public JDialog getRegisterDialog(){
        return registerDialog;
    }
    //Listeners for Register
    public void addRegisterAccountListener(ActionListener listener){
        this.registerButton.addActionListener(listener);
    }
    
//Win/Loss Dialog
    public JButton getMainMenuButton(){
        return mainMenuButton;
    }
    public JButton getExitButton(){
        return exitButton;
    }
    public JDialog getWinLossDialog(){
        return WinLossDialog;
    }
    //Listeners for Win/Loss
    public void addMainMenuListener(ActionListener listener){
        this.mainMenuButton.addActionListener(listener);
    }
    
    public void addExitListener(MouseListener listener){
        this.exitButton.addMouseListener(listener);
    }
    
//MainMenu Panel
    public JPanel getMainMenuPanel() {
        return mainMenuPanel;
    }
    public JButton getPlayMainMenuButton(){
        return playMainMenuButton;
    }
    public JButton getExitMainMenuButton(){
        return exitMainMenuButton;
    }
    //Listeners for Main Menu
    public void addPlayMainMenuListener(ActionListener listener){
        this.playMainMenuButton.addActionListener(listener);
    }
    
    public void addExitMainMenuListener(MouseListener listener){
        this.exitMainMenuButton.addMouseListener(listener);
    }

//User Info Internal Frame
    public JInternalFrame getUserInfoInternalFrame(){
        return userInfoInternalFrame;
    }
    public JLabel getUserInfoUsername(){
        return userInfoUsername;
    }
    public JMenuItem getUserInfoMenuBarDeleteAccount(){
        return userInfoMenuBarDelete;
    }
    public void addDeleteUserListener(ActionListener listener) {
        this.userInfoMenuBarDelete.addActionListener(listener);
    }

//Settings Dialog
    public JButton getMainMenuSettingsButton(){
        return mainMenuSettingsButton;
    }
    public JButton getResumeSettingsButton(){
        return resumeSettingsButton;
    }
    public JDialog getSettingsDialog(){
        return SettingsDialog;
    }
    //Listeners for Win/Loss
    public void addMainMenuSettingsListener(ActionListener listener){
        this.mainMenuSettingsButton.addActionListener(listener);
    }
    
    public void addResumeSettingsListener(MouseListener listener){
        this.resumeSettingsButton.addMouseListener(listener);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        registerDialog = new javax.swing.JDialog();
        registerLabel = new javax.swing.JLabel();
        registerUsernameField = new javax.swing.JTextField();
        registerUsernameLabel = new javax.swing.JLabel();
        registerPasswordLabel = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        registerPasswordField = new javax.swing.JPasswordField();
        WinLossDialog = new javax.swing.JDialog();
        winLossLabel = new javax.swing.JLabel();
        mainMenuButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        mainMenuPanel = new javax.swing.JPanel();
        SuperSuvivorMainMenuLabel = new javax.swing.JLabel();
        playMainMenuButton = new javax.swing.JButton();
        exitMainMenuButton = new javax.swing.JButton();
        userInfoInternalFrame = new javax.swing.JInternalFrame();
        userInfoUsername = new javax.swing.JLabel();
        userInfoMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        userInfoMenuBarDelete = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        SettingsDialog = new javax.swing.JDialog();
        settingsLabel = new javax.swing.JLabel();
        mainMenuSettingsButton = new javax.swing.JButton();
        resumeSettingsButton = new javax.swing.JButton();
        DesktopPane = new javax.swing.JDesktopPane();
        loginInternalFrame = new javax.swing.JInternalFrame();
        loginLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        createAccountLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();

        registerDialog.setBackground(new java.awt.Color(51, 255, 204));

        registerLabel.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLabel.setText("Register Account");

        registerUsernameLabel.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        registerUsernameLabel.setText("Username");

        registerPasswordLabel.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        registerPasswordLabel.setText("Password");

        registerButton.setBackground(new java.awt.Color(0, 0, 0));
        registerButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Create");

        javax.swing.GroupLayout registerDialogLayout = new javax.swing.GroupLayout(registerDialog.getContentPane());
        registerDialog.getContentPane().setLayout(registerDialogLayout);
        registerDialogLayout.setHorizontalGroup(
            registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerDialogLayout.createSequentialGroup()
                .addGroup(registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registerPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(registerDialogLayout.createSequentialGroup()
                            .addGap(77, 77, 77)
                            .addGroup(registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(registerUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(registerUsernameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registerPasswordLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(registerDialogLayout.createSequentialGroup()
                            .addGap(199, 199, 199)
                            .addComponent(registerButton))))
                .addContainerGap(75, Short.MAX_VALUE))
            .addComponent(registerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        registerDialogLayout.setVerticalGroup(
            registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerDialogLayout.createSequentialGroup()
                .addComponent(registerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(registerUsernameLabel)
                .addGap(3, 3, 3)
                .addComponent(registerUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerButton)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        winLossLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
        winLossLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winLossLabel.setText("Win/Loss");

        mainMenuButton.setBackground(new java.awt.Color(255, 255, 255));
        mainMenuButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        mainMenuButton.setText("Main Menu");

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        exitButton.setText("Exit");

        javax.swing.GroupLayout WinLossDialogLayout = new javax.swing.GroupLayout(WinLossDialog.getContentPane());
        WinLossDialog.getContentPane().setLayout(WinLossDialogLayout);
        WinLossDialogLayout.setHorizontalGroup(
            WinLossDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WinLossDialogLayout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addGroup(WinLossDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(198, 198, 198))
            .addComponent(winLossLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        WinLossDialogLayout.setVerticalGroup(
            WinLossDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WinLossDialogLayout.createSequentialGroup()
                .addComponent(winLossLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
        );

        mainMenuPanel.setBackground(new java.awt.Color(102, 255, 102));

        SuperSuvivorMainMenuLabel.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        SuperSuvivorMainMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SuperSuvivorMainMenuLabel.setText("SuperSurvivor");

        playMainMenuButton.setBackground(new java.awt.Color(255, 255, 255));
        playMainMenuButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        playMainMenuButton.setText("Play");

        exitMainMenuButton.setBackground(new java.awt.Color(255, 255, 255));
        exitMainMenuButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        exitMainMenuButton.setText("Exit");

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SuperSuvivorMainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exitMainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playMainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addComponent(SuperSuvivorMainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(playMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(exitMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        userInfoInternalFrame.setBackground(new java.awt.Color(255, 255, 153));
        userInfoInternalFrame.setVisible(true);

        userInfoUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userInfoUsername.setText("Username!");

        userInfoMenuBar.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("File");

        userInfoMenuBarDelete.setText("Delete Account");
        jMenu1.add(userInfoMenuBarDelete);

        userInfoMenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        userInfoMenuBar.add(jMenu2);

        userInfoInternalFrame.setJMenuBar(userInfoMenuBar);

        javax.swing.GroupLayout userInfoInternalFrameLayout = new javax.swing.GroupLayout(userInfoInternalFrame.getContentPane());
        userInfoInternalFrame.getContentPane().setLayout(userInfoInternalFrameLayout);
        userInfoInternalFrameLayout.setHorizontalGroup(
            userInfoInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userInfoUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );
        userInfoInternalFrameLayout.setVerticalGroup(
            userInfoInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoInternalFrameLayout.createSequentialGroup()
                .addComponent(userInfoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 379, Short.MAX_VALUE))
        );

        settingsLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
        settingsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingsLabel.setText("Settings");

        mainMenuSettingsButton.setBackground(new java.awt.Color(255, 255, 255));
        mainMenuSettingsButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        mainMenuSettingsButton.setText("Main Menu");

        resumeSettingsButton.setBackground(new java.awt.Color(255, 255, 255));
        resumeSettingsButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        resumeSettingsButton.setText("Resume");

        javax.swing.GroupLayout SettingsDialogLayout = new javax.swing.GroupLayout(SettingsDialog.getContentPane());
        SettingsDialog.getContentPane().setLayout(SettingsDialogLayout);
        SettingsDialogLayout.setHorizontalGroup(
            SettingsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsDialogLayout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addGroup(SettingsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mainMenuSettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addComponent(resumeSettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(198, 198, 198))
            .addComponent(settingsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SettingsDialogLayout.setVerticalGroup(
            SettingsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsDialogLayout.createSequentialGroup()
                .addComponent(settingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(mainMenuSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(resumeSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginInternalFrame.setBackground(new java.awt.Color(51, 255, 204));
        loginInternalFrame.setVisible(true);
        loginInternalFrame.getContentPane().setLayout(new java.awt.GridBagLayout());

        loginLabel.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("SuperSurvivor Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 157, 0, 0);
        loginInternalFrame.getContentPane().add(loginLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 588;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 117, 0, 0);
        loginInternalFrame.getContentPane().add(usernameField, gridBagConstraints);

        usernameLabel.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        usernameLabel.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 117, 0, 0);
        loginInternalFrame.getContentPane().add(usernameLabel, gridBagConstraints);

        passwordLabel.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        passwordLabel.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 117, 0, 0);
        loginInternalFrame.getContentPane().add(passwordLabel, gridBagConstraints);

        loginButton.setBackground(new java.awt.Color(0, 0, 0));
        loginButton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Submit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 121, 51, 0);
        loginInternalFrame.getContentPane().add(loginButton, gridBagConstraints);

        createAccountLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        createAccountLabel.setText("Click here to Register an Account");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 263, 0, 0);
        loginInternalFrame.getContentPane().add(createAccountLabel, gridBagConstraints);

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 586;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 117, 0, 136);
        loginInternalFrame.getContentPane().add(passwordField, gridBagConstraints);

        DesktopPane.setLayer(loginInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginInternalFrame)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JDialog SettingsDialog;
    private javax.swing.JLabel SuperSuvivorMainMenuLabel;
    private javax.swing.JDialog WinLossDialog;
    private javax.swing.JLabel createAccountLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitMainMenuButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JButton loginButton;
    private javax.swing.JInternalFrame loginInternalFrame;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JButton mainMenuSettingsButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton playMainMenuButton;
    private javax.swing.JButton registerButton;
    private javax.swing.JDialog registerDialog;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JPasswordField registerPasswordField;
    private javax.swing.JLabel registerPasswordLabel;
    private javax.swing.JTextField registerUsernameField;
    private javax.swing.JLabel registerUsernameLabel;
    private javax.swing.JButton resumeSettingsButton;
    private javax.swing.JLabel settingsLabel;
    private javax.swing.JInternalFrame userInfoInternalFrame;
    private javax.swing.JMenuBar userInfoMenuBar;
    private javax.swing.JMenuItem userInfoMenuBarDelete;
    private javax.swing.JLabel userInfoUsername;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel winLossLabel;
    // End of variables declaration//GEN-END:variables
}
