
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tonyh
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

//JFrame - Desktop Pane + Login
    public JDesktopPane getDesktopPane(){
        return DesktopPane;
    }
    public JInternalFrame getLoginInternalFrame(){
        return loginInternalFrame;
    }
    public JTextField getLoginUsername(){
        return usernameField;
    }
    public JTextField getLoginPassword(){
        return passwordField;
    }
    public JButton getLoginButton(){
        return loginButton;
    }
    public JLabel getCreateAccountButton(){
        return createAccountLabel;
    }
    //Listeners for Login
    public void addsubmitListener(ActionListener listener){
        this.loginButton.addActionListener(listener);
    }
    
    public void addregisterListener(MouseListener listener){
        this.createAccountLabel.addMouseListener(listener);
    }

//Register Dialog
    public JTextField getRegisterUsername(){
        return registerUsernameField;
    }
    public JTextField getRegisterPassword(){
        return registerPasswordField;
    }
    public JButton getRegisterButton(){
        return registerButton;
    }
    public JDialog getRegisterDialog(){
        return registerDialog;
    }
    //Listeners for Register
    public void addRegisterAccountListener(ActionListener listener){
        this.registerButton.addActionListener(listener);
    }
    
//Win/Loss Dialog
    public JButton getMainMenuButton(){
        return mainMenuButton;
    }
    public JButton getExitButton(){
        return exitButton;
    }
    public JDialog getWinLossDialog(){
        return WinLossDialog;
    }
    //Listeners for Win/Loss
    public void addMainMenuListener(ActionListener listener){
        this.mainMenuButton.addActionListener(listener);
    }
    
    public void addExitListener(MouseListener listener){
        this.exitButton.addMouseListener(listener);
    }
    
//MainMenu Panel
    public JButton getPlayMainMenuButton(){
        return playMainMenuButton;
    }
    public JButton getExitMainMenuButton(){
        return exitMainMenuButton;
    }
    //Listeners for Main Menu
    public void addPlayMainMenuListener(ActionListener listener){
        this.playMainMenuButton.addActionListener(listener);
    }
    
    public void addExitMainMenuListener(MouseListener listener){
        this.exitMainMenuButton.addMouseListener(listener);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        registerDialog = new javax.swing.JDialog();
        registerLabel = new javax.swing.JLabel();
        registerUsernameField = new javax.swing.JTextField();
        registerUsernameLabel = new javax.swing.JLabel();
        registerPasswordLabel = new javax.swing.JLabel();
        registerPasswordField = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        WinLossDialog = new javax.swing.JDialog();
        winLossLabel = new javax.swing.JLabel();
        mainMenuButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        mainMenuPanel = new javax.swing.JPanel();
        SuperSuvivorMainMenuLabel = new javax.swing.JLabel();
        playMainMenuButton = new javax.swing.JButton();
        exitMainMenuButton = new javax.swing.JButton();
        DesktopPane = new javax.swing.JDesktopPane();
        loginInternalFrame = new javax.swing.JInternalFrame();
        loginLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        createAccountLabel = new javax.swing.JLabel();

        registerDialog.setBackground(new java.awt.Color(102, 255, 204));

        registerLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLabel.setText("Register Account");

        registerUsernameLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        registerUsernameLabel.setText("Username");

        registerPasswordLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        registerPasswordLabel.setText("Password");

        registerButton.setBackground(new java.awt.Color(0, 0, 0));
        registerButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Create");

        javax.swing.GroupLayout registerDialogLayout = new javax.swing.GroupLayout(registerDialog.getContentPane());
        registerDialog.getContentPane().setLayout(registerDialogLayout);
        registerDialogLayout.setHorizontalGroup(
            registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerDialogLayout.createSequentialGroup()
                .addGroup(registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerDialogLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registerPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(registerUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(registerUsernameLabel)
                                    .addComponent(registerPasswordLabel)))))
                    .addGroup(registerDialogLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(registerButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerDialogLayout.createSequentialGroup()
                .addGap(0, 55, Short.MAX_VALUE)
                .addComponent(registerLabel)
                .addGap(51, 51, 51))
        );
        registerDialogLayout.setVerticalGroup(
            registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerDialogLayout.createSequentialGroup()
                .addComponent(registerLabel)
                .addGap(31, 31, 31)
                .addComponent(registerUsernameLabel)
                .addGap(3, 3, 3)
                .addComponent(registerUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        winLossLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        winLossLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winLossLabel.setText("Win/Loss");

        mainMenuButton.setText("Main Menu");

        exitButton.setText("Exit");

        javax.swing.GroupLayout WinLossDialogLayout = new javax.swing.GroupLayout(WinLossDialog.getContentPane());
        WinLossDialog.getContentPane().setLayout(WinLossDialogLayout);
        WinLossDialogLayout.setHorizontalGroup(
            WinLossDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WinLossDialogLayout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(WinLossDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WinLossDialogLayout.createSequentialGroup()
                        .addComponent(winLossLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WinLossDialogLayout.createSequentialGroup()
                        .addGroup(WinLossDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                            .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(198, 198, 198))))
        );
        WinLossDialogLayout.setVerticalGroup(
            WinLossDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WinLossDialogLayout.createSequentialGroup()
                .addComponent(winLossLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
        );

        SuperSuvivorMainMenuLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        SuperSuvivorMainMenuLabel.setText("SuperSurvivor");

        playMainMenuButton.setText("PLAY");

        exitMainMenuButton.setText("EXIT");

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPanelLayout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addComponent(SuperSuvivorMainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addComponent(SuperSuvivorMainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(playMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(exitMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 133, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DesktopPane.setLayout(new javax.swing.OverlayLayout(DesktopPane));

        loginInternalFrame.setBackground(new java.awt.Color(51, 255, 204));
        loginInternalFrame.setVisible(true);
        loginInternalFrame.getContentPane().setLayout(new java.awt.GridBagLayout());

        loginLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("SuperSurvivor Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 157, 0, 0);
        loginInternalFrame.getContentPane().add(loginLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 588;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 117, 0, 122);
        loginInternalFrame.getContentPane().add(usernameField, gridBagConstraints);

        usernameLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        usernameLabel.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 117, 0, 0);
        loginInternalFrame.getContentPane().add(usernameLabel, gridBagConstraints);

        passwordLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        passwordLabel.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 117, 0, 0);
        loginInternalFrame.getContentPane().add(passwordLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 588;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 117, 0, 122);
        loginInternalFrame.getContentPane().add(passwordField, gridBagConstraints);

        loginButton.setBackground(new java.awt.Color(0, 0, 0));
        loginButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Submit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 121, 22, 0);
        loginInternalFrame.getContentPane().add(loginButton, gridBagConstraints);

        createAccountLabel.setText("Click here to Register an Account");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 16, 0, 122);
        loginInternalFrame.getContentPane().add(createAccountLabel, gridBagConstraints);

        DesktopPane.add(loginInternalFrame);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JLabel SuperSuvivorMainMenuLabel;
    private javax.swing.JDialog WinLossDialog;
    private javax.swing.JLabel createAccountLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitMainMenuButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JInternalFrame loginInternalFrame;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton playMainMenuButton;
    private javax.swing.JButton registerButton;
    private javax.swing.JDialog registerDialog;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JTextField registerPasswordField;
    private javax.swing.JLabel registerPasswordLabel;
    private javax.swing.JTextField registerUsernameField;
    private javax.swing.JLabel registerUsernameLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel winLossLabel;
    // End of variables declaration//GEN-END:variables
}
